name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklash
        uses: actions/checkout@v4

      - name: SSH kalitni sozlash
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Serverga deploy qilish
        env:
          HOST: ${{secrets.HOST}}
          USER: ${{secrets.USERNAME}}
          APP_DIR: /elbek/ci_cd
          PORT: ${{secrets.PORT}}
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh $USER@$HOST "
            # Node va npm o'rnatilganligini tekshirish
            if ! command -v node >/dev/null 2>&1; then
              echo 'Node.js o‘rnatilyapti...'
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # pm2 o'rnatilganligini tekshirish
            if ! command -v pm2 >/dev/null 2>&1; then
              echo 'PM2 o‘rnatilyapti...'
              sudo npm install -g pm2
            fi

            # Loyihani yuklash yoki yangilash
            if [ ! -d $APP_DIR ]; then
              mkdir -p $APP_DIR
              git clone https://github.com/elbekdamirov/ci_cd.git $APP_DIR
              cd $APP_DIR   
              echo 'PORT=${PORT}' > .env
            else
              cd $APP_DIR
              git pull origin main
            fi

            npm install
            npm run build

            # pm2 restart yoki start
            pm2 restart ci_cd_app_elbek || pm2 start dist/main.js --name ci_cd_app_elbek
          "
        shell: bash
