name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Lint check
        run: npm run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Test check
        env:
          PORT: ${{ secrets.PORT }}
        run: npm run test
